/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ca.uvic.seng330.ex7;

public class Driver {

  public static void main(String[] args) {
    Points pObj = new Points();

    //change this so these run on separate threads.
    PointsClient c1 = new CricketPointsClient(pObj);
    PointsClient c2 = new CricketPointsClient(pObj);
    PointsClient c3 = new FootballPointsClient(pObj);

    for (int i = 0; i < 1000; i++) {
      c1.scores(1);
      c2.assists(1);
      c1.assists(pObj.getPoints()-1);
      c3.scores(pObj.getPoints()-1);
      c3.assists(pObj.getPoints()-1);

    }

    System.out.println(pObj.getPoints());
  }

}
